### ISSUE TITLE
DydxApiError(status_code=401, response={'errors': [{'msg': 'Unauthorized'}]})

### ISSUE THREAD

**Issue by xldistance** [dydxprotocol/dydx-v3-python#197]
I get this error when I test querying an order
```
https://api.dydx.exchange/v3/orders?market=['BTC-USD']&status=['PENDING', 'OPEN']
Traceback (most recent call last):
  File "H:\Desktop\dydx测试.py", line 22, in <module>
    orders = private_client.private.get_orders(market = ["BTC-USD"],status = ["PENDING","OPEN"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\dydx3\modules\private.py", line 356, in get_orders
    return self._get(
           ^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\dydx3\modules\private.py", line 78, in _get
    return self._private_request(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\dydx3\modules\private.py", line 69, in _private_request
    return request(
           ^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\dydx3\helpers\requests.py", line 34, in request
    raise DydxApiError(response)
dydx3.errors.DydxApiError: DydxApiError(status_code=401, response={'errors': [{'msg': 'Unauthorized'}]})
```

**Comment by xldistance** [comment]
I have entered the key, secret and passphrase in api_key_credentials, and stark_private_key, stark_public_key

**Comment by xldistance** [comment]
![QQ截图20230219131045](https://user-images.githubusercontent.com/29418474/219923466-8cc35ffa-34cf-4ca7-9ddb-22fce4dbe8d7.png)

**Comment by aryanve** [comment]
Did you find the solution ?

**Comment by xldistance** [comment]
> Did you find the solution ?

There is a problem with the official documentation, I remember changing it to status=['PENDING']
